"use client";
import { AppCtxType } from "@/lib/models";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createContext, useState } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const AppCtx = createContext<AppCtxType | null>(null);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [bills, setBills] = useState<AppCtxType["billCached"]>(null);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppCtx.Provider value={{ billCached: bills, setBillCached: setBills }}>
          <div className="flex flex-col h-screen px-4 py-6">{children}</div>
          <Toaster position="top-center" reverseOrder={false} gutter={8} />
        </AppCtx.Provider>
      </body>
    </html>
  );
}
